export interface Event {
    uid : string,
    uuid : string,
    dateStart : string,
    timeStarts : string,
    duration : string,
    location : string,
    zipcode : string,
    complement : string,
    street : string,
    neighborhood : string,
    city : string,
    state : string,
    country : string,
    lat : string,
    lng : string,
    attendees : number,
    type : string,
    number : string,

    valorTotal : number,

    //staff
    qtdBartender : number,
    qtdGarcom : number,
    qtdAjudante : number,
    qtdRecepcionista : number,
    qtdChurrasqueiro : number,
    valTotalBartender : number,
    valTotalGarcom : number,
    valTotalAjudante : number,
    valTotalRecepcionista : number,
    valTotalChurrasqueiro : number,
    valBartender : number,
    valGarcom : number,
    valAjudante : number,
    valRecepcionista : number,
    valChurrasqueiro : number,
    //services
    qtdBurguer : number,
    qtdPizza : number,
    qtdCrepe : number,
    qtdAgua : number,
    qtdCerveja : number,
    qtdGin : number,
    valTotalBurguer : number,
    valTotalPizza : number,
    valTotalCrepe : number,
    valTotalAgua : number,
    valTotalCerveja : number,
    valTotalGin : number,
    valBurguer : number,
    valPizza : number,
    valCrepe : number,
    valAgua : number,
    valCerveja : number,
    valGin : number
  }
